CREATE DATABASE customer_behavior;
SELECT * FROM customers limit 20;

-- Q1. What is the total revenue generated by male vs female customers? 
select gender, sum(purchase_amount) as revenue
from customers
group by gender

-- Q2. Which customers used a discount but still spend more than the average purchase amount?
SELECT customer_id, purchase_amount
from customers
WHERE discount_applied = 'Yes' and purchase_amount >= (SELECT AVG(purchase_amount) FROM customers) 

-- Q3. Which are the top 5 product with the highest avg review rating?
select item_purchased, round(avg(review_rating),2) as 'Average Product Review'
from customers
group by item_purchased
order by avg(review_rating) desc
limit 5

-- Q4. Compare the average purchase amount between the standard and express shipping.
select shipping_type, round(avg(purchase_amount),2) as average_revenue from customers
where shipping_type in ('Express','Standard')
group by shipping_type

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between
-- subscribers and non-subscribers
select subscription_status,
 count(customer_id) as total_customer,
 round(avg(purchase_amount),2) as avg_revenue,
 sum(purchase_amount) as total_revenue
 from customers
 group by subscription_status
 order by total_revenue, avg_revenue desc;
 
 -- Q6. Which 5 products have the highest percentage of purchases with discount applied?
 select item_purchased,
 round((sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*))*100,2) as discount_rate
 from customers
 group by item_purchased
 order by discount_rate desc
 limit 5;
 
 -- Q7. Segment customer new, returnung  and loyal base on their previous total purchase
 -- and show the count of their each segment
 with customer_type as (
 select customer_id, previous_purchases,
 case
	when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from customers
 )
 select customer_segment, count(*) as 'Number of Customer'
 from customer_type
 group by customer_segment
 
 -- Q8. What are the top 3 most purchased product within each category?
 with ProductRanking as(
	select
    category,
    item_purchased,
    count(*) as total_purchased,
	ROW_NUMBER() OVER(PARTITION BY category ORDER BY count(*) DESC) 
    AS product_rank
    from customers
    group by category, item_purchased
    )
    select category, item_purchased, total_purchased, product_rank
    from ProductRanking
    where product_rank<=3
    
-- Q9. Are customeres who are repeat buyers(more than 5 previous purchase) likely to subscribers?
select subscription_status,
count(customer_id) as repeat_buyers
from customers
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customers
group by age_group
order by total_revenue desc
 